server:
  port: 10018
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: order-service #路由ID 自己定义就行 要唯一
          uri: lb://order-service #路由目标地址
          predicates: #路由规则
            - Path=/api/order/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
    #切换gateway的负载均衡器为ReactiveLoadBalancerClientFilter
    loadbalancer:
      ribbon:
        enabled: false

