server:
  port: 1013
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root123456
  redis:
    database: 1
    host: 127.0.0.1
    #    host: 47.98.117.173
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
      lettuce:
        shutdown-timeout: 0
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: SX #配置集群

logging:
  level:
    com.xz.mapper: DEBUG
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#mybatis配置
mybatis:
  typeAliasesPackage: com.xz.po
  mapperLocations: classpath:mapper/*.xml

